import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { FiltersProvider } from '~/context/FiltersContext';
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Pokémons",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <FiltersProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </FiltersProvider>
      </body>
    </html>
  );
}
